#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
#disable caps lock
setxkbmap -option ctrl:nocaps

#redshift
pgrep redshift | xargs -n1 kill -9
redshift -x 
redshift &

# panel
pkill polybar
polybar -c "$HOME/.config/bspwm/polybar.ini" &

# background
feh --bg-fill --randomize "$HOME/Pictures/wallpapers/" &

pkill picom
picom -b &

systemctl --user import-environment DISPLAY
pkill clipmenud
clipmenud &

# set some bsp specific
bspc monitor -d 1 2 3 4 5

bspc config window_gap 16
bspc config border_width 2

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true

bspc config normal_border_color "#85642c"
bspc config focused_border_color "#F0C674"

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Emacs state=tiled
bspc rule -a firefox desktop=^1 focus=off
bspc rule -a Slack desktop=^5 focus=off
bspc rule -a Spotify desktop=^5 focus=off
bspc rule -a jetbrains-idea desktop=^2 focus=off
bspc rule -a pavucontrol state=floating


bspc subscribe desktop_layout |
    while read -r _ _ _ l; do
        case $l in monocle)
           picom-trans --reset;; tiled)
        esac;
    done
