#! /bin/bash

# Send internal monitor as first param and external as second
function switch_monitor () {
    if [[ $(xrandr -q | grep "^$2 connected") ]]; then
        xrandr --output "$2" --mode 3840x2160 --primary && xrandr --output "$1" --off
        bspc desktop "$1" --to-monitor "$2"
    else
        xrandr --output "$1" --mode 1920x1080 --primary && xrandr --output "$2" --off
        bspc desktop "$2" --to-monitor "$1"
    fi
}

HOST=`hostname`
case "$HOST" in
    endive)
        switch_monitor "eDP-1" "DP-1"
        ;;
    archie)
        switch_monitor "eDP1" "DP1"
        ;;
esac

bspc wm -r

