#! /bin/bash

set -e

# Send internal monitor as first param and external as second
function switch_monitor () {
    if [[ $(xrandr -q | grep "^$2 connected") ]]; then
        xrandr --output "$2" --mode 3840x2160 --fb 3840x2160 --primary && xrandr --output "$1" --off
        bspc desktop "$1" --to-monitor "$2"
    else
        xrandr --output "$1" --mode 1920x1080 --fb 1920x1080 --primary && xrandr --output "$2" --off
        bspc desktop "$2" --to-monitor "$1"
    fi
}

function handle_slartibartfast() {
    if [[ $(xrandr -q | grep "^DP-2 connected") ]]; then
        RESOLUTION=$(xrandr | grep -A 1 "^DP-2 connected" | tail -n 1 | awk '{print $1}' | sort -Vr | head -n 1)
        xrandr --output DP-2 --mode $RESOLUTION --primary && xrandr --output eDP-1 --off
        bspc desktop eDP-1 --to-monitor DP-2
    elif [[ $(xrandr -q | grep "^DP-3 connected") ]]; then
        RESOLUTION=$(xrandr | grep -A 1 "^DP-3 connected" | tail -n 1 | awk '{print $1}' | sort -Vr | head -n 1)
        xrandr --output DP-3 --mode $RESOLUTION --primary && xrandr --output eDP-1 --off
        bspc desktop eDP-1 --to-monitor DP-3
    else
        OLD=$(xrandr --query | grep " connected primary" | cut -d' ' -f1)
        xrandr --output eDP-1 --mode 1920x1200 --primary --fb 1920x1200 && xrandr --output "$OLD" --off
        bspc desktop "$OLD" --to-monitor eDP-1
    fi
}

HOST=`hostname`
case "$HOST" in
    endive)
        switch_monitor "eDP-1" "DP-1"
        ;;
    archie)
        switch_monitor "eDP1" "DP1"
        ;;
    slartibartfast)
        handle_slartibartfast
        ;;
esac

bspc wm -r


